//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soltys.Service.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IGenerateMatrixService")]
    public interface IGenerateMatrixService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenerateMatrixService/GenerateMatrix", ReplyAction="http://tempuri.org/IGenerateMatrixService/GenerateMatrixResponse")]
        Soltys.MatrixService.DTO.MatrixRes GenerateMatrix(int rows, int columns);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenerateMatrixService/GenerateMatrix", ReplyAction="http://tempuri.org/IGenerateMatrixService/GenerateMatrixResponse")]
        System.Threading.Tasks.Task<Soltys.MatrixService.DTO.MatrixRes> GenerateMatrixAsync(int rows, int columns);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenerateMatrixService/GenerateMatrixWithId", ReplyAction="http://tempuri.org/IGenerateMatrixService/GenerateMatrixWithIdResponse")]
        int GenerateMatrixWithId(int rows, int columns);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenerateMatrixService/GenerateMatrixWithId", ReplyAction="http://tempuri.org/IGenerateMatrixService/GenerateMatrixWithIdResponse")]
        System.Threading.Tasks.Task<int> GenerateMatrixWithIdAsync(int rows, int columns);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenerateMatrixService/GetMatrixById", ReplyAction="http://tempuri.org/IGenerateMatrixService/GetMatrixByIdResponse")]
        Soltys.MatrixService.DTO.MatrixRes GetMatrixById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenerateMatrixService/GetMatrixById", ReplyAction="http://tempuri.org/IGenerateMatrixService/GetMatrixByIdResponse")]
        System.Threading.Tasks.Task<Soltys.MatrixService.DTO.MatrixRes> GetMatrixByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGenerateMatrixServiceChannel : Soltys.Service.ServiceReference1.IGenerateMatrixService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GenerateMatrixServiceClient : System.ServiceModel.ClientBase<Soltys.Service.ServiceReference1.IGenerateMatrixService>, Soltys.Service.ServiceReference1.IGenerateMatrixService {
        
        public GenerateMatrixServiceClient() {
        }
        
        public GenerateMatrixServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GenerateMatrixServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenerateMatrixServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenerateMatrixServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Soltys.MatrixService.DTO.MatrixRes GenerateMatrix(int rows, int columns) {
            return base.Channel.GenerateMatrix(rows, columns);
        }
        
        public System.Threading.Tasks.Task<Soltys.MatrixService.DTO.MatrixRes> GenerateMatrixAsync(int rows, int columns) {
            return base.Channel.GenerateMatrixAsync(rows, columns);
        }
        
        public int GenerateMatrixWithId(int rows, int columns) {
            return base.Channel.GenerateMatrixWithId(rows, columns);
        }
        
        public System.Threading.Tasks.Task<int> GenerateMatrixWithIdAsync(int rows, int columns) {
            return base.Channel.GenerateMatrixWithIdAsync(rows, columns);
        }
        
        public Soltys.MatrixService.DTO.MatrixRes GetMatrixById(int id) {
            return base.Channel.GetMatrixById(id);
        }
        
        public System.Threading.Tasks.Task<Soltys.MatrixService.DTO.MatrixRes> GetMatrixByIdAsync(int id) {
            return base.Channel.GetMatrixByIdAsync(id);
        }
    }
}
