//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soltys.Service.Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMatrixService")]
    public interface IMatrixService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatrixService/MultiplyMatrix", ReplyAction="http://tempuri.org/IMatrixService/MultiplyMatrixResponse")]
        Soltys.MatrixService.DTO.MatrixRes MultiplyMatrix(Soltys.MatrixService.DTO.MathMatrix a, Soltys.MatrixService.DTO.MathMatrix b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatrixService/MultiplyMatrix", ReplyAction="http://tempuri.org/IMatrixService/MultiplyMatrixResponse")]
        System.Threading.Tasks.Task<Soltys.MatrixService.DTO.MatrixRes> MultiplyMatrixAsync(Soltys.MatrixService.DTO.MathMatrix a, Soltys.MatrixService.DTO.MathMatrix b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatrixService/MultiplyMatrixById", ReplyAction="http://tempuri.org/IMatrixService/MultiplyMatrixByIdResponse")]
        Soltys.MatrixService.DTO.MatrixRes MultiplyMatrixById(int aId, int bId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatrixService/MultiplyMatrixById", ReplyAction="http://tempuri.org/IMatrixService/MultiplyMatrixByIdResponse")]
        System.Threading.Tasks.Task<Soltys.MatrixService.DTO.MatrixRes> MultiplyMatrixByIdAsync(int aId, int bId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatrixService/GenerateMatrix", ReplyAction="http://tempuri.org/IMatrixService/GenerateMatrixResponse")]
        Soltys.MatrixService.DTO.MatrixRes GenerateMatrix(int rows, int columns);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatrixService/GenerateMatrix", ReplyAction="http://tempuri.org/IMatrixService/GenerateMatrixResponse")]
        System.Threading.Tasks.Task<Soltys.MatrixService.DTO.MatrixRes> GenerateMatrixAsync(int rows, int columns);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatrixService/GenerateMatrixWithId", ReplyAction="http://tempuri.org/IMatrixService/GenerateMatrixWithIdResponse")]
        int GenerateMatrixWithId(int rows, int columns);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatrixService/GenerateMatrixWithId", ReplyAction="http://tempuri.org/IMatrixService/GenerateMatrixWithIdResponse")]
        System.Threading.Tasks.Task<int> GenerateMatrixWithIdAsync(int rows, int columns);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatrixService/GetMatrixById", ReplyAction="http://tempuri.org/IMatrixService/GetMatrixByIdResponse")]
        Soltys.MatrixService.DTO.MatrixRes GetMatrixById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatrixService/GetMatrixById", ReplyAction="http://tempuri.org/IMatrixService/GetMatrixByIdResponse")]
        System.Threading.Tasks.Task<Soltys.MatrixService.DTO.MatrixRes> GetMatrixByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatrixServiceChannel : Soltys.Service.Client.ServiceReference1.IMatrixService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatrixServiceClient : System.ServiceModel.ClientBase<Soltys.Service.Client.ServiceReference1.IMatrixService>, Soltys.Service.Client.ServiceReference1.IMatrixService {
        
        public MatrixServiceClient() {
        }
        
        public MatrixServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MatrixServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatrixServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatrixServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Soltys.MatrixService.DTO.MatrixRes MultiplyMatrix(Soltys.MatrixService.DTO.MathMatrix a, Soltys.MatrixService.DTO.MathMatrix b) {
            return base.Channel.MultiplyMatrix(a, b);
        }
        
        public System.Threading.Tasks.Task<Soltys.MatrixService.DTO.MatrixRes> MultiplyMatrixAsync(Soltys.MatrixService.DTO.MathMatrix a, Soltys.MatrixService.DTO.MathMatrix b) {
            return base.Channel.MultiplyMatrixAsync(a, b);
        }
        
        public Soltys.MatrixService.DTO.MatrixRes MultiplyMatrixById(int aId, int bId) {
            return base.Channel.MultiplyMatrixById(aId, bId);
        }
        
        public System.Threading.Tasks.Task<Soltys.MatrixService.DTO.MatrixRes> MultiplyMatrixByIdAsync(int aId, int bId) {
            return base.Channel.MultiplyMatrixByIdAsync(aId, bId);
        }
        
        public Soltys.MatrixService.DTO.MatrixRes GenerateMatrix(int rows, int columns) {
            return base.Channel.GenerateMatrix(rows, columns);
        }
        
        public System.Threading.Tasks.Task<Soltys.MatrixService.DTO.MatrixRes> GenerateMatrixAsync(int rows, int columns) {
            return base.Channel.GenerateMatrixAsync(rows, columns);
        }
        
        public int GenerateMatrixWithId(int rows, int columns) {
            return base.Channel.GenerateMatrixWithId(rows, columns);
        }
        
        public System.Threading.Tasks.Task<int> GenerateMatrixWithIdAsync(int rows, int columns) {
            return base.Channel.GenerateMatrixWithIdAsync(rows, columns);
        }
        
        public Soltys.MatrixService.DTO.MatrixRes GetMatrixById(int id) {
            return base.Channel.GetMatrixById(id);
        }
        
        public System.Threading.Tasks.Task<Soltys.MatrixService.DTO.MatrixRes> GetMatrixByIdAsync(int id) {
            return base.Channel.GetMatrixByIdAsync(id);
        }
    }
}
